cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

lingerie_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.new_arrivals, name='index'),
    path('shop', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %} Lingerie store {% endblock title %}</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="description" content="Wish shop project">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static '/styles/bootstrap4/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/plugins/OwlCarousel2-2.2.1/animate.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/plugins/colorbox/colorbox.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/styles/main_styles.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/styles/responsive.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/styles/cart.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/styles/cart_responsive.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/styles/product.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/styles/product_responsive.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/styles/checkout.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/styles/checkout_responsive.css' %}">
	</head>
<body>
	<div class="super_container">
	
	<!-- Header -->

	<header class="header">
		<div class="header_inner d-flex flex-row align-items-center justify-content-start">
			<div class="logo"><a href="{% url 'shop:index' %}">Lingerie</a></div>
			<nav class="main_nav">
				<ul>
					<li><a href="{% url 'shop:index' %}">главная</a></li>
					<li><a href="categories.html">clothes</a></li>
					<li><a href="categories.html">accessories</a></li>
					<li><a href="categories.html">lingerie</a></li>
					<li><a href="contact.html">contact</a></li>
				</ul>
			</nav>
			<div class="header_content ml-auto">
				<div class="search header_search">
					<form action="#">
						<input type="search" class="search_input" required="required">
						<button type="submit" id="search_button" class="search_button"><img src="{% static '/images/magnifying-glass.svg' %}" alt=""></button>
					</form>
				</div>
				<div class="shopping">
					<!-- Cart -->
					{% with total_items=cart|length %}
						<a href="{% url 'cart:cart_detail' %}">
							<div class="cart">
								<img src="{% static '/images/shopping-bag.svg' %}">
								<div class="cart_num_container">
									<div class="cart_num_inner">
										<div class="cart_num">{% if total_items > 0 %}{{ cart.get_total_price }} BYN {% else %} 0 BYN {% endif %}
										</div>
									</div>
								</div>
							</div>
						</a>
					{% endwith %}
					<!-- Star -->
					<a href="#">
						<div class="star">
							<img src="{% static '/images/star.svg' %}" alt="">
							<div class="star_num_container">
								<div class="star_num_inner">
									<div class="star_num">0</div>
								</div>
							</div>
						</div>
					</a>
					<!-- Avatar -->
					<a href="#">
						<div class="avatar">
							<img src="{% static '/images/avatar.svg' %}" alt="">
						</div>
					</a>
				</div>
			</div>

			<div class="burger_container d-flex flex-column align-items-center justify-content-around menu_mm"><div></div><div></div><div></div></div>
		</div>
	</header>

		<!-- Menu -->

	<div class="menu d-flex flex-column align-items-end justify-content-start text-right menu_mm trans_400">
		<div class="menu_close_container"><div class="menu_close"><div></div><div></div></div></div>
		<div class="logo menu_mm"><a href="{% url 'shop:index' %}">Lingerie</a></div>
		<div class="search">
			<form action="#">
				<input type="search" class="search_input menu_mm" required="required">
				<button type="submit" id="search_button_menu" class="search_button menu_mm"><img class="menu_mm" src="{% static '/images/magnifying-glass.svg' %}" alt=""></button>
			</form>
		</div>
		<nav class="menu_nav">
			<ul class="menu_mm">
				<li class="menu_mm"><a href="{% url 'shop:index' %}">главная</a></li>
				<li class="menu_mm"><a href="#">clothes</a></li>
				<li class="menu_mm"><a href="#">accessories</a></li>
				<li class="menu_mm"><a href="#">lingerie</a></li>
				<li class="menu_mm"><a href="#">contact</a></li>
			</ul>
		</nav>
	</div>
	
{% block content %}

{% endblock content %}

<!-- Footer -->

	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col text-center">
					<div class="footer_logo"><a href="{% url 'shop:index' %}">Lingerie</a></div>
					<nav class="footer_nav">
						<ul>
							<li><a href="{% url 'shop:index' %}">главная</a></li>
							<li><a href="categories.html">clothes</a></li>
							<li><a href="categories.html">accessories</a></li>
							<li><a href="categories.html">lingerie</a></li>
							<li><a href="contact.html">contact</a></li>
						</ul>
					</nav>
					<div class="footer_social">
						<ul>
							<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-reddit-alien" aria-hidden="true"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						</ul>
					</div>
					<div class="copyright"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
					</div>
				</div>
			</div>
		</div>
	</footer>

	<script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static '/styles/bootstrap4/popper.js' %}"></script>
	<script src="{% static '/styles/bootstrap4/bootstrap.min.js' %}"></script>
	<script src="{% static '/plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
	<script src="{% static '/plugins/easing/easing.js' %}"></script>
	<script src="{% static '/plugins/parallax-js-master/parallax.min.js' %}"></script>
	<script src="{% static '/plugins/colorbox/jquery.colorbox-min.js' %}"></script>
	<script src="{% static '/js/custom.js' %}"></script>
	<script src="{% static '/js/product_custom.js' %}"></script>
	<script src="{% static '/js/checkout_custom.js' %}"></script>
</body>
</html>